// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as activity$0 from "./internal/activity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloads$0 from "./internal/downloads/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jobs$0 from "./internal/jobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "./internal/library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as psn$0 from "./internal/psn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rpcs3$0 from "./internal/rpcs3/models.js";

export function ActivityLog(): $CancellablePromise<activity$0.Entry[]> {
    return $Call.ByID(1985337110).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AutoDetectGamesYML returns the first detected RPCS3 games.yml path on this
 * system, or empty string if none of the common locations exist.
 */
export function AutoDetectGamesYML(): $CancellablePromise<string> {
    return $Call.ByID(2383501306);
}

export function CancelJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(1182131210, id);
}

export function ClearActivityLog(): $CancellablePromise<void> {
    return $Call.ByID(2022669751);
}

export function ClearActivityLogScope(scope: string): $CancellablePromise<void> {
    return $Call.ByID(3747848757, scope);
}

export function ConfigFilePath(): $CancellablePromise<string> {
    return $Call.ByID(1273835914);
}

export function DeleteLibraryItems(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(73741487, paths);
}

export function EnqueueDownload(req: jobs$0.Request): $CancellablePromise<string> {
    return $Call.ByID(124622777, req);
}

export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(1200034045).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * InstallLibraryPKGsPS3 installs only Library PKGs newer than the
 * version currently present in RPCS3.
 */
export function InstallLibraryPKGsPS3(): $CancellablePromise<number> {
    return $Call.ByID(2930352174);
}

export function ListDownloadLibrary(): $CancellablePromise<downloads$0.Title[]> {
    return $Call.ByID(526952512).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListFirmware fetches the region-fanned firmware list for the given mode.
 * Modes: "ps3" | "ps4" | "ps5" | "psvita".
 */
export function ListFirmware(mode: string): $CancellablePromise<psn$0.FirmwareList | null> {
    return $Call.ByID(3950208416, mode).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListJobs(): $CancellablePromise<jobs$0.Job[]> {
    return $Call.ByID(4257729417).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListRPCS3Library parses the configured (or auto-detected) games.yml and
 * returns one entry per registered title. Returns an empty list when no
 * path is configured/found, with an error message in the second return so
 * the frontend can render the appropriate empty state.
 */
export function ListRPCS3Library(): $CancellablePromise<rpcs3$0.Entry[]> {
    return $Call.ByID(2767185793).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * OpenFolder opens the given directory in the system's file manager.
 * Cross-platform: Explorer on Windows, `open` on macOS, `xdg-open` on Linux.
 * `path` may start with ~ (expanded against the user home dir). If the path
 * does not exist the OS file manager will surface its own error.
 */
export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3894305329, path);
}

export function PauseJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(1505341468, id);
}

/**
 * PendingLibraryPKGsPS3 returns the number of Library PKGs newer than their
 * installed RPCS3 versions.
 */
export function PendingLibraryPKGsPS3(): $CancellablePromise<number> {
    return $Call.ByID(1032921658);
}

export function PickDirectory(title: string, defaultDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(1347829059, title, defaultDirectory);
}

export function PickGamesYML(defaultDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(4015052751, defaultDirectory);
}

/**
 * ReconcileTitlePS3 resolves one already-parsed RPCS3 row so the frontend can
 * publish the local games.yml list immediately and fill server state per row.
 */
export function ReconcileTitlePS3(entry: rpcs3$0.Entry): $CancellablePromise<library$0.Row> {
    return $Call.ByID(566170611, entry).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ResumeJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(3849492309, id);
}

export function RetryJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(2012971368, id);
}

/**
 * SaveConfig persists config and applies runtime settings to active clients.
 */
export function SaveConfig(next: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(3442292638, next);
}

export function SearchPS3(tid: string, includeDRMFree: boolean): $CancellablePromise<psn$0.Title | null> {
    return $Call.ByID(156335737, tid, includeDRMFree).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SearchPS4(tid: string): $CancellablePromise<psn$0.Title | null> {
    return $Call.ByID(173113356, tid).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SearchVita(tid: string): $CancellablePromise<psn$0.Title | null> {
    return $Call.ByID(1407672275, tid).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SyncAllPS3 removes title folders not represented in the already-loaded RPCS3
 * list, then synchronizes each title without reloading games.yml.
 */
export function SyncAllPS3(entries: rpcs3$0.Entry[]): $CancellablePromise<string[]> {
    return $Call.ByID(2563320289, entries).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SyncTitlePS3 makes one already-loaded RPCS3 title exactly match the PKGs
 * advertised by the server without reloading games.yml.
 */
export function SyncTitlePS3(tid: string): $CancellablePromise<string[]> {
    return $Call.ByID(2047523786, tid).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ValidateSettingsPath(kind: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1423002005, kind, path);
}

// Private type creation functions
const $$createType0 = activity$0.Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = downloads$0.Title.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = psn$0.FirmwareList.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = jobs$0.Job.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = rpcs3$0.Entry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = library$0.Row.createFrom;
const $$createType12 = psn$0.Title.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($Create.Any);
