// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as psn$0 from "../psn/models.js";

/**
 * Job is a single download+verify unit; there is no auto-install chain.
 */
export class Job {
    "id": string;
    "title_id": string;
    "title_name"?: string;
    "mode": string;
    "locale"?: string;
    "kind"?: string;
    "update": psn$0.Update;
    "dest_path": string;
    "state": JobState;
    "downloaded": number;
    "error"?: string;
    "throughput"?: number;
    "eta"?: number;
    "attempt"?: number;
    "max_attempts"?: number;

    /** Creates a new Job instance. */
    constructor($$source: Partial<Job> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title_id" in $$source)) {
            this["title_id"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("update" in $$source)) {
            this["update"] = (new psn$0.Update());
        }
        if (!("dest_path" in $$source)) {
            this["dest_path"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = JobState.$zero;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     */
    static createFrom($$source: any = {}): Job {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField6_0($$parsedSource["update"]);
        }
        return new Job($$parsedSource as Partial<Job>);
    }
}

export enum JobState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateQueued = "queued",
    StateDownloading = "downloading",
    StatePaused = "paused",
    StateResuming = "resuming",
    StateVerifying = "verifying",
    StateDone = "done",
    StateFailed = "failed",
    StateCanceled = "canceled",
};

/**
 * Request is the frontend-facing payload to enqueue a job.
 */
export class Request {
    "title_id": string;
    "title_name"?: string;
    "mode": string;
    "locale"?: string;
    "kind"?: string;
    "update": psn$0.Update;

    /** Creates a new Request instance. */
    constructor($$source: Partial<Request> = {}) {
        if (!("title_id" in $$source)) {
            this["title_id"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("update" in $$source)) {
            this["update"] = (new psn$0.Update());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     */
    static createFrom($$source: any = {}): Request {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField5_0($$parsedSource["update"]);
        }
        return new Request($$parsedSource as Partial<Request>);
    }
}

// Private type creation functions
const $$createType0 = psn$0.Update.createFrom;
