// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "rpcs3": RPCS3;
    "storage": Storage;
    "network": Network;
    "ui": UI;

    /**
     * HomeDir is not stored in config.toml; it is populated in-memory at load
     * so the UI can show resolved absolute paths (e.g. C:\Users\you\.psnwdl\…)
     * instead of the literal ~/ the frontend used to fall back to.
     */
    "home_dir": string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("rpcs3" in $$source)) {
            this["rpcs3"] = (new RPCS3());
        }
        if (!("storage" in $$source)) {
            this["storage"] = (new Storage());
        }
        if (!("network" in $$source)) {
            this["network"] = (new Network());
        }
        if (!("ui" in $$source)) {
            this["ui"] = (new UI());
        }
        if (!("home_dir" in $$source)) {
            this["home_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rpcs3" in $$parsedSource) {
            $$parsedSource["rpcs3"] = $$createField0_0($$parsedSource["rpcs3"]);
        }
        if ("storage" in $$parsedSource) {
            $$parsedSource["storage"] = $$createField1_0($$parsedSource["storage"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField2_0($$parsedSource["network"]);
        }
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField3_0($$parsedSource["ui"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class Network {
    "max_concurrent_downloads": number;
    "verify_tls": boolean;
    "request_timeout_seconds": number;
    "retry_count": number;

    /** Creates a new Network instance. */
    constructor($$source: Partial<Network> = {}) {
        if (!("max_concurrent_downloads" in $$source)) {
            this["max_concurrent_downloads"] = 0;
        }
        if (!("verify_tls" in $$source)) {
            this["verify_tls"] = false;
        }
        if (!("request_timeout_seconds" in $$source)) {
            this["request_timeout_seconds"] = 0;
        }
        if (!("retry_count" in $$source)) {
            this["retry_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Network instance from a string or object.
     */
    static createFrom($$source: any = {}): Network {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Network($$parsedSource as Partial<Network>);
    }
}

export class RPCS3 {
    "games_yml": string;
    "hdd0_game": string;

    /** Creates a new RPCS3 instance. */
    constructor($$source: Partial<RPCS3> = {}) {
        if (!("games_yml" in $$source)) {
            this["games_yml"] = "";
        }
        if (!("hdd0_game" in $$source)) {
            this["hdd0_game"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RPCS3 instance from a string or object.
     */
    static createFrom($$source: any = {}): RPCS3 {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RPCS3($$parsedSource as Partial<RPCS3>);
    }
}

export class Storage {
    "library_dir": string;

    /** Creates a new Storage instance. */
    constructor($$source: Partial<Storage> = {}) {
        if (!("library_dir" in $$source)) {
            this["library_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Storage instance from a string or object.
     */
    static createFrom($$source: any = {}): Storage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Storage($$parsedSource as Partial<Storage>);
    }
}

export class UI {
    "theme": string;
    "default_mode": string;
    "default_download": string;

    /** Creates a new UI instance. */
    constructor($$source: Partial<UI> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("default_mode" in $$source)) {
            this["default_mode"] = "";
        }
        if (!("default_download" in $$source)) {
            this["default_download"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UI instance from a string or object.
     */
    static createFrom($$source: any = {}): UI {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UI($$parsedSource as Partial<UI>);
    }
}

// Private type creation functions
const $$createType0 = RPCS3.createFrom;
const $$createType1 = Storage.createFrom;
const $$createType2 = Network.createFrom;
const $$createType3 = UI.createFrom;
