// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is one line in the activity console. Ts is an RFC3339 timestamp
 * string rather than time.Time so the Wails TS model generator produces a
 * clean `string` (the generator has no mapping for time.Time and logs a
 * noisy "Not found: time.Time" on every run). The frontend parses it with
 * `new Date(ts)`, which handles RFC3339 fine.
 */
export class Entry {
    "ts": string;
    "level": Level;
    "scope": string;
    "message": string;
    "job_id"?: string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("ts" in $$source)) {
            this["ts"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = Level.$zero;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelInfo = "info",
    LevelWarn = "warn",
    LevelError = "error",
};
