//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as activity$0 from "../../../../../PSNWDL/internal/activity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../../../../PSNWDL/internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloads$0 from "../../../../../PSNWDL/internal/downloads/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jobs$0 from "../../../../../PSNWDL/internal/jobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../../../../../PSNWDL/internal/library/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "activity:log": $$createType0,
        "config:updated": $$createType1,
        "downloads:updated": $$createType3,
        "job:added": $$createType4,
        "job:progress": $$createType4,
        "job:state": $$createType4,
        "library:updated": $$createType6,
    }));
}

// Private type creation functions
const $$createType0 = activity$0.Entry.createFrom;
const $$createType1 = config$0.Config.createFrom;
const $$createType2 = downloads$0.Title.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = jobs$0.Job.createFrom;
const $$createType5 = library$0.Row.createFrom;
const $$createType6 = $Create.Array($$createType5);

configure();
