// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as activity$0 from "../../../../../PSNWDL/internal/activity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as config$0 from "../../../../../PSNWDL/internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as downloads$0 from "../../../../../PSNWDL/internal/downloads/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as jobs$0 from "../../../../../PSNWDL/internal/jobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as library$0 from "../../../../../PSNWDL/internal/library/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "activity:log": activity$0.Entry;
            "config:updated": config$0.Config;
            "downloads:error": string;
            "downloads:updated": downloads$0.Title[];
            "job:added": jobs$0.Job;
            "job:progress": jobs$0.Job;
            "job:state": jobs$0.Job;
            "library:error": string;
            "library:updated": library$0.Row[];
        }
    }
}
