// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is a single game registered in RPCS3's games.yml.
 */
export class Entry {
    "title_id": string;
    "install_dir": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("title_id" in $$source)) {
            this["title_id"] = "";
        }
        if (!("install_dir" in $$source)) {
            this["install_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}
