// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class File {
    "path": string;
    "name": string;
    "size": number;
    "version"?: string;
    "kind"?: string;

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File($$parsedSource as Partial<File>);
    }
}

export class Title {
    "mode": string;
    "title_id": string;
    "path": string;
    "file_count": number;
    "total_size": number;
    "latest_version"?: string;
    "files": File[];

    /** Creates a new Title instance. */
    constructor($$source: Partial<Title> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("title_id" in $$source)) {
            this["title_id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("file_count" in $$source)) {
            this["file_count"] = 0;
        }
        if (!("total_size" in $$source)) {
            this["total_size"] = 0;
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Title instance from a string or object.
     */
    static createFrom($$source: any = {}): Title {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField6_0($$parsedSource["files"]);
        }
        return new Title($$parsedSource as Partial<Title>);
    }
}

// Private type creation functions
const $$createType0 = File.createFrom;
const $$createType1 = $Create.Array($$createType0);
