// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FirmwareEntry describes a single firmware PUP available from Sony's CDN.
 */
export class FirmwareEntry {
    "locale": string;
    "type"?: string;
    "version": string;
    "url": string;
    "size"?: number;
    "sha1sum"?: string;

    /** Creates a new FirmwareEntry instance. */
    constructor($$source: Partial<FirmwareEntry> = {}) {
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FirmwareEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FirmwareEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FirmwareEntry($$parsedSource as Partial<FirmwareEntry>);
    }
}

/**
 * FirmwareList is the merged, deduplicated result of a firmware lookup across
 * all locales for one console.
 */
export class FirmwareList {
    /**
     * "ps3" | "ps4" | "ps5" | "psvita"
     */
    "console": string;
    "entries": FirmwareEntry[];

    /** Creates a new FirmwareList instance. */
    constructor($$source: Partial<FirmwareList> = {}) {
        if (!("console" in $$source)) {
            this["console"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FirmwareList instance from a string or object.
     */
    static createFrom($$source: any = {}): FirmwareList {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new FirmwareList($$parsedSource as Partial<FirmwareList>);
    }
}

/**
 * Title is the resolved lookup result for a single PSN title ID.
 */
export class Title {
    "id": string;
    "name"?: string;
    "updates": Update[];

    /** Creates a new Title instance. */
    constructor($$source: Partial<Title> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("updates" in $$source)) {
            this["updates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Title instance from a string or object.
     */
    static createFrom($$source: any = {}): Title {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updates" in $$parsedSource) {
            $$parsedSource["updates"] = $$createField2_0($$parsedSource["updates"]);
        }
        return new Title($$parsedSource as Partial<Title>);
    }
}

/**
 * Update describes a single title-update package as advertised by Sony.
 */
export class Update {
    "version": string;
    "size": number;
    "sha1sum": string;
    "url": string;
    "system_version"?: string;
    "drm_type"?: string;

    /** Creates a new Update instance. */
    constructor($$source: Partial<Update> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("sha1sum" in $$source)) {
            this["sha1sum"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Update instance from a string or object.
     */
    static createFrom($$source: any = {}): Update {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Update($$parsedSource as Partial<Update>);
    }
}

// Private type creation functions
const $$createType0 = FirmwareEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Update.createFrom;
const $$createType3 = $Create.Array($$createType2);
