// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivityLog() {
  return window['go']['main']['App']['ActivityLog']();
}

export function AutoDetectGamesYML() {
  return window['go']['main']['App']['AutoDetectGamesYML']();
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function ClearActivityLog() {
  return window['go']['main']['App']['ClearActivityLog']();
}

export function ClearTitleCache(arg1) {
  return window['go']['main']['App']['ClearTitleCache'](arg1);
}

export function ConfigFilePath() {
  return window['go']['main']['App']['ConfigFilePath']();
}

export function DeleteLibraryItems(arg1) {
  return window['go']['main']['App']['DeleteLibraryItems'](arg1);
}

export function EnqueueDownload(arg1) {
  return window['go']['main']['App']['EnqueueDownload'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function InstallFolderPS3(arg1, arg2) {
  return window['go']['main']['App']['InstallFolderPS3'](arg1, arg2);
}

export function InstallJob(arg1) {
  return window['go']['main']['App']['InstallJob'](arg1);
}

export function ListDownloadLibrary() {
  return window['go']['main']['App']['ListDownloadLibrary']();
}

export function ListFirmware(arg1) {
  return window['go']['main']['App']['ListFirmware'](arg1);
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function ListRPCS3Library() {
  return window['go']['main']['App']['ListRPCS3Library']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PauseJob(arg1) {
  return window['go']['main']['App']['PauseJob'](arg1);
}

export function PickDirectory(arg1, arg2) {
  return window['go']['main']['App']['PickDirectory'](arg1, arg2);
}

export function PickGamesYML(arg1) {
  return window['go']['main']['App']['PickGamesYML'](arg1);
}

export function ReconcileLibraryPS3() {
  return window['go']['main']['App']['ReconcileLibraryPS3']();
}

export function ResumeJob(arg1) {
  return window['go']['main']['App']['ResumeJob'](arg1);
}

export function RetryJob(arg1) {
  return window['go']['main']['App']['RetryJob'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchPS3(arg1, arg2) {
  return window['go']['main']['App']['SearchPS3'](arg1, arg2);
}

export function SearchPS4(arg1) {
  return window['go']['main']['App']['SearchPS4'](arg1);
}

export function SearchVita(arg1) {
  return window['go']['main']['App']['SearchVita'](arg1);
}

export function SetActiveMode(arg1) {
  return window['go']['main']['App']['SetActiveMode'](arg1);
}

export function SyncTitlePS3(arg1) {
  return window['go']['main']['App']['SyncTitlePS3'](arg1);
}

export function UpdateDownloadLibrary() {
  return window['go']['main']['App']['UpdateDownloadLibrary']();
}

export function ValidateSettingsPath(arg1, arg2) {
  return window['go']['main']['App']['ValidateSettingsPath'](arg1, arg2);
}
