// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {activity} from '../models';
import {jobs} from '../models';
import {config} from '../models';
import {downloads} from '../models';
import {psn} from '../models';
import {rpcs3} from '../models';
import {library} from '../models';

export function ActivityLog():Promise<Array<activity.Entry>>;

export function AutoDetectGamesYML():Promise<string>;

export function CancelJob(arg1:string):Promise<void>;

export function ClearActivityLog():Promise<void>;

export function ClearTitleCache(arg1:string):Promise<void>;

export function ConfigFilePath():Promise<string>;

export function DeleteLibraryItems(arg1:Array<string>):Promise<void>;

export function EnqueueDownload(arg1:jobs.Request):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function InstallFolderPS3(arg1:string,arg2:string):Promise<void>;

export function InstallJob(arg1:string):Promise<void>;

export function ListDownloadLibrary():Promise<Array<downloads.Title>>;

export function ListFirmware(arg1:string):Promise<psn.FirmwareList>;

export function ListJobs():Promise<Array<jobs.Job>>;

export function ListRPCS3Library():Promise<Array<rpcs3.Entry>>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseJob(arg1:string):Promise<void>;

export function PickDirectory(arg1:string,arg2:string):Promise<string>;

export function PickGamesYML(arg1:string):Promise<string>;

export function ReconcileLibraryPS3():Promise<Array<library.Row>>;

export function ResumeJob(arg1:string):Promise<void>;

export function RetryJob(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SearchPS3(arg1:string,arg2:boolean):Promise<psn.Title>;

export function SearchPS4(arg1:string):Promise<psn.Title>;

export function SearchVita(arg1:string):Promise<psn.Title>;

export function SetActiveMode(arg1:string):Promise<void>;

export function SyncTitlePS3(arg1:string):Promise<void>;

export function UpdateDownloadLibrary():Promise<Array<downloads.Title>>;

export function ValidateSettingsPath(arg1:string,arg2:string):Promise<void>;
